### ISSUE TITLE
OSD feature (push changes)

### ISSUE THREAD

**Issue by nik0** [EliasKotlyar/Xiaomi-Dafang-Software#2]
Hi EliasKotlyar,
I have worked on a OSD display. I am not very familiar with Github, do you want I submit a new branch (I am not sure you want me to push on the master ...)
Thanks,

Nik0

**Comment by EliasKotlyar** [comment]
You cannot work on my "master" branch, unless i give you access to. Just work on your fork, and then create a pull-request. I will merge it when , and release a new binary.

**Comment by nik0** [comment]
Did it. Hope it is working ...
