### ISSUE TITLE
Building tun/tap kernel driver

### ISSUE THREAD

**Issue by ZigFisher** [EliasKotlyar/Xiaomi-Dafang-Software#30]
Good afternoon !
Please tell me how I can build a tun/tap driver (tun.ko) for this kernel.
Thank you !

P.S. I write this ask in other [repo](https://github.com/Dafang-Hacks/kernel), sorry.

**Comment by nik0** [comment]
There was a discussion about compiling drivers here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/236

**Comment by ZigFisher** [comment]
Good Job !
Many TNX !
