### ISSUE TITLE
Motion

### ISSUE THREAD

**Issue by nik0** [EliasKotlyar/Xiaomi-Dafang-Software#4]
I am trying to get running the motion detection sample. 
I have a crash when calling the API IMP_IVS_CreateChn
Any idea how to debug ?
Thanks,

Nik0

**Comment by EliasKotlyar** [comment]
Try to go down with the resolution. Its often run out of memory due to bad configuration of the bootloader

**Comment by nik0** [comment]
No, still the same ... :-(

**Comment by nik0** [comment]
I succeed compiled strace (it doesn't help in my case), but it can be used by someone else ...
[strace.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/files/1607334/strace.zip)

**Comment by EliasKotlyar** [comment]
@nik0 : Have a look at the Api-Manual which is located in the T20 Repository(docs.zip). I suppose the face-recognition should run on the "second" channel.
![typical_application](https://user-images.githubusercontent.com/9529505/35777353-bfaf7878-09ac-11e8-82c0-0f498a12e2c2.png)

**Comment by iashwinprasada** [comment]
Yes, that seems to be the problem. Let me look into this and possibly integrate it.

**Comment by nik0** [comment]
In the function sample_ivs_move_start
I have un-commented the / 2 like this:
`                        param.roiRect[j * 2 + i].p0.x = i * param.frameInfo.width  / 2 ;
                        param.roiRect[j * 2 + i].p0.y = j * param.frameInfo.height  / 2 ;
                        param.roiRect[j * 2 + i].p1.x = (i + 1) * param.frameInfo.width  / 2  - 1;
                        param.roiRect[j * 2 + i].p1.y = (j + 1) * param.frameInfo.height  / 2  - 1;
`
and it seems to work !
I have this output:
`frame[0], result->retRoi(0,0,0,0)
frame[1], result->retRoi(0,0,0,0)
frame[2], result->retRoi(0,0,0,0)
frame[3], result->retRoi(0,0,0,0)
frame[4], result->retRoi(0,0,0,0)
frame[5], result->retRoi(1,1,1,1)
frame[6], result->retRoi(0,0,0,0)
frame[7], result->retRoi(0,0,0,0)
frame[8], result->retRoi(1,1,1,1)
frame[9], result->retRoi(0,0,0,0)
`
and 1,1,1,1 is when I put my hand in front of the camera.
For now I didn't succeed having the same code running on v4l2rtspserver-master :-(

Nik0

**Comment by nik0** [comment]
Bingo ! I succeeded 
I create a pull request for motion detection. Not sure to understood all the APIs but it seems to be working.
I set the region detection to the whole picture.
You need to create 2 scripts that are started when motion detected ON or when OFF
There is no "security" on starting X times the same script, and no check of the presence of these ...
Maybe on this script you can save the movie, send an email, ....

**Comment by iashwinprasada** [comment]
Great. I will test it out too

**Comment by nobet78** [comment]
@nik0 can I ask for a tutorial?

**Comment by nik0** [comment]
What do you mean by a tutorial ?
Until my pull request is not merged, you need to compile the binary and push it to the camera.
Then the detection is activated (you can see some logs). 
Then you can create a script like this: /system/sdcard/scripts/detectionOn.sh
#!/bin/sh
echo -n "Detection !!!" >>  /tmp/detect.txt
date >> /tmp/detect.txt

then you can check the file /tmp/detect.txt that will have the detected events ....

Hope it helps,
Nik0

**Comment by nobet78** [comment]
I do not know how to do it, I will wait

**Comment by nik0** [comment]
I've updated the whole process. It should work correctly (hopefully)
I added some configuration through setconf
I tried to plug avconv on the "on" script but I have this log, and that's it:
`[rtsp @ 0x19d18e0] CSeq 6 expected, 0 received.
`
