### ISSUE TITLE
How to implement multiple stream encoder

### ISSUE THREAD

**Issue by iashwinprasada** [EliasKotlyar/Xiaomi-Dafang-Software#5]
I was reading the ingenic product sheet and see that it supports multiple streams for h264.

Max resolution 2048*2048
Up to H.264 1080P@60fps encode
H.264 multiple streams: 1080P@30fps+D1@30fps+JPEG@15fps
ABR/VBR/CBR/CQP
8 ROIs, 5-layer OSD with hardware

This could be used to run two rtsp servers? Or use the second source to record on board DVR videos? 

Can you point me in the right direction about his to tweak the encoder to output two independent streams that can be used simultaneously?

**Comment by iashwinprasada** [comment]
i tried changing the **FS_CHN_NUM to 2** and set the profile to baseline **enc_attr->profile = 0**; from the imp-samples. but it's not working for me, im getting this out put when i run the sample encoder
![image](https://user-images.githubusercontent.com/8593605/34852579-ab494272-f72f-11e7-8591-2e4ff006a631.png)

**Comment by iashwinprasada** [comment]
ok! i have got two streams working with the modified uboot i found from [Issue](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/30). I'll update what happens

**Comment by dbuxo** [comment]
Could this second stream be used to take snapshots while the rtsp server is running on the first one?

**Comment by iashwinprasada** [comment]
Yeah that's the plan, it should be possible!

**Comment by iashwinprasada** [comment]
@EliasKotlyar 
I see that from the v4l2rtspserver > main.cpp I need to add a for loop that adds multiple streams? And also change the encoder to provide relevant frames. Can you suggest if it's the right direction?

**Comment by iashwinprasada** [comment]
@EliasKotlyar i have been trying to approuch this by modifying the ImpEncoder from your v4l2rtspserver src. Here is how it looks https://pastebin.com/qMnWhL0N 

i'm not able to understand what the IMP_Encoder_StartRecvPic(1); is doing. can you help?

**Comment by EliasKotlyar** [comment]
Check the kernel logs(cat /proc/kmsg or something similar) to find out the reason for that. Maybe there is a lack of memory. Try to reduce the resolution. Maybe start with both streams using 320x240.

**Comment by EliasKotlyar** [comment]
Hello @iashwinprasada ,

I managed to get two streams working. It can be used to watch a H264-Stream and also take MJPEG Shot. It was much easier than expected. The hint is: read the manual. There is a description how to make it work. You can find it in "docs.zip" in the T20 Repository.

**Comment by iashwinprasada** [comment]
That's great. I'll have a look into the docs too. I was having trouble making it work with v4l2rtspserver. I'll check now. Thanks!
