### ISSUE TITLE
Why Boa and not httpd in busybox?

### ISSUE THREAD

**Issue by Cabalist** [EliasKotlyar/Xiaomi-Dafang-Software#9]
Boa ceased development 13 years ago as far as I can tell. Why is it being used instead of busybox’s own httpd?

**Comment by nik0** [comment]
You can use busybox if you want but it is also obsolete:
In run.sh change the line:

`## Start Webserver:                                     
#/system/sdcard/bin/boa -c /system/sdcard/config/                                                          
/system/sdcard/bin/busybox httpd -c /system/sdcard/config/httpd2.conf -p 7000 -h /system/sdcard/www/  
`
You can use the default httpd2.conf here (I tested it) https://wiki.openwrt.org/doc/howto/http.httpd

But we may try to go to http://www.lighttpd.net/

**Comment by Cabalist** [comment]
Thanks!  Lighttpd would be even better! :)

**Comment by nik0** [comment]
I compiled it, I need to test it ...

**Comment by nik0** [comment]
See my pull request https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/221
